In [ ]:
import numpy as np


In [ ]:
# time needed with additional money
M = np.array([
[0,15,20,18,25],
[5,12,16,15,21],
[10,9,13,12,18],
[15,8,11,10,16],
[20,7,9,9,14],
[25,6,8,8,12],
[30,5,7,7,11],
[35,4,7,6,10]
])
n=4    # number of projects
m=len(M)    # number of budgests


In [ ]:
V=np.zeros((m,n))  # for value of total completion time given budget
p = np.zeros((m,n)) # the optimal decision of budgests given to 4 projects given remaining budget
V[:,n-1]=M[:,n]  # given budgets, the toal completion time if can only do the last project
p[:,n-1] = range(m)  # optimal value
print(M)
print(V)

[[ 0 15 20 18 25]
 [ 5 12 16 15 21]
 [10  9 13 12 18]
 [15  8 11 10 16]
 [20  7  9  9 14]
 [25  6  8  8 12]
 [30  5  7  7 11]
 [35  4  7  6 10]]
[[ 0.  0.  0. 25.]
 [ 0.  0.  0. 21.]
 [ 0.  0.  0. 18.]
 [ 0.  0.  0. 16.]
 [ 0.  0.  0. 14.]
 [ 0.  0.  0. 12.]
 [ 0.  0.  0. 11.]
 [ 0.  0.  0. 10.]]


In [ ]:
for t in range(n-2,-1,-1):
    
    for s in range(m): #[0,7]
        #p[s,t]=0
        V[s,t] = M[0,t+1]+V[s,t+1]
        if s>0:
            for k in range(1,s+1):  # loop over budgets [1,7] 
                if(V[s,t] > M[k,t+1] +V[int(s-k),t+1] ):  # total completion time of t and after with budget s 
                    V[s,t] = M[k,t+1] +V[int(s-k),t+1]    #  is min {time for project t given $k  and projects after t given $s-k}
                    
                    p[s,t]=k
s=7
x=[]
for i in range(4):
    x.append(p[int(s),i])
    s=s-p[int(s),i]
V

array([[78., 63., 43., 25.],
       [74., 59., 39., 21.],
       [70., 55., 36., 18.],
       [67., 52., 33., 16.],
       [64., 49., 30., 14.],
       [61., 46., 28., 12.],
       [58., 43., 26., 11.],
       [55., 41., 24., 10.]])

In [ ]:
for t in range(n-2,-1,-1):
    
    for s in range(m): #[0,7]
        #p[s,t]=0
        V[s,t] = M[0,t+1]+V[s,t+1]
        
        for k in range(1,s+1):  # loop over budgets [1,7] 
            if(V[s,t] > M[k,t+1] +V[int(s-k),t+1] ):  # total completion time of t and after with budget s 
                V[s,t] = M[k,t+1] +V[int(s-k),t+1]    #  is min {time for project t given $k  and projects after t given $s-k}
                    
                p[s,t]=k
s=7
x=[]
for i in range(4):
    x.append(p[int(s),i])
    s=s-p[int(s),i]
V

array([[78., 63., 43., 25.],
       [74., 59., 39., 21.],
       [70., 55., 36., 18.],
       [67., 52., 33., 16.],
       [64., 49., 30., 14.],
       [61., 46., 28., 12.],
       [58., 43., 26., 11.],
       [55., 41., 24., 10.]])