In [1]:
import numpy as np
from scipy.stats import binom as binom

### Solutions to Problem 2 betting

In [2]:
from scipy.stats import binom

In [3]:
x = 10
p=0.4
z = binom.pmf(np.arange(x),x,p)
print((1-p)**10)
print(z)

0.006046617599999997
[0.00604662 0.04031078 0.12093235 0.21499085 0.25082266 0.20065812
 0.11147674 0.04246733 0.01061683 0.00157286]


In [4]:
# initial wealth
W = 4
p = 0.4

# number of rounds
n = 2

# maximum wealth after n rounds
Wmax = (2**n)*W

# target wealth after n rounds
Wn = 7


In [5]:
V = np.zeros((Wmax+1,n+1))
pi = np.zeros((Wmax+1,n))

In [6]:
V[:,n] = (np.arange(Wmax+1) >= Wn)
print(V)
for t in range(n-1,-1,-1):
    for s in range((2**t)*W+1): # maximum possible wealth at time t is (2^t)*W 
        V[s,t] = V[s,t+1] # invest zero in this round
        pi[s,t] = 0;
        for x in range(1,s+1):
            z = np.array(binom.pmf(np.arange(x+1),x,p))
            nextState = 2*np.arange(x+1) + s - x
            if (z@V[nextState,t+1] > V[s,t]):
                V[s,t] = z@V[nextState,t+1]
                pi[s,t] = x


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


### Solutions to Problem 3
fatest path

In [7]:
C = np.array([
     [np.Inf, 5, 3, 12, 9],
     [5, np.Inf, 7, 10, 2],
     [3, 7, np.Inf, 4, 7],
     [10, 9, 4, np.Inf, 1],
     [7, 2, 8, 1, np.Inf]
])
n = np.shape(C)[0]

In [8]:
n

5

In [9]:
V = np.zeros((n,n))
pi = np.zeros(n)
V[:,0] = C[:,0]


In [13]:
s = 0
for t in range(1,n):
    for k in range(n):
        if (k != s):
            V[k,t] = V[k,t-1]
            for l in range(n):
                if (min([V[l,t-1],C[l,k]]) > V[k,t]):
                    V[k,t] = min([V[l,t-1],C[l,k]])
                    pi[k] = l
pi

array([0., 3., 4., 0., 0.])